version: '3.8'
services:

  fastapi:
    image: sakdahomhuan/fastapi:latest
    container_name: fastapi
    working_dir: /app/
    volumes:
      - ./app/:/app/
    ports:
      - 8000:80
    command: /start-reload.sh
